### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by joeyliao127**
廖致皓，完成第二階段第一週作業。
instance IP: 35.174.190.247
http://35.174.190.247:3000/api/attractions?page=0
http://35.174.190.247:3000/api/attractions?page=0&keyword=台
http://35.174.190.247:3000/api/attraction/10
http://35.174.190.247:3000/api/mrts

### CODE REVIEW

**Review by cwpeng — COMMENTED** [review]
Your server is down. Re-request review after you fixed it.

**Comment by joeyliao127** [comment]
The server is running. The problem was that I added a rule only allowing only my home's ip to send http requests.
Howerver, I have removed the restriction. Please review my assignment again.

**Comment by cwpeng** [comment]
Re-request review from top right corner in this pull request so that I can review for you.

**Review by cwpeng — COMMENTED** [review]
http://35.174.190.247:3000/api/attractions?page=1&keyword=%E5%8C%97 should contain some data. We want to find out attractions where keyword is in attraction title, not only prefixed.

Fix it and re-request review.

**Review by cwpeng — CHANGES_REQUESTED** [review]
`nextPage` field of http://35.174.190.247:3000/api/attractions?page=0&keyword=%E5%8C%97 should be 1, because second page is available.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
