### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by joeyliao127**
Joey 廖致皓
http://44.219.72.138:3000/
http://44.219.72.138:3000/attraction/2

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your server.

**Comment by joeyliao127** [comment]
I have restarted service. Please try again.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Border style of sign in/up form should align with design.

**Comment by joeyliao127** [comment]
I have changed button style.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by joeyliao127** [comment]
Thanks

**Pull request merged**
