### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by joeyliao127**
Joey 廖致皓
http://44.219.72.138:3000/
http://44.219.72.138:3000/attraction/2
http://44.219.72.138:3000/booking

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Just refresh /booking page after deleting booking data.

**Comment by joeyliao127** [comment]
bugfix
clicking delete and signout will refresh on the same page.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by joeyliao127** [comment]
thanks

**Pull request merged**
